# Generated by Django 4.2.5 on 2023-09-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BienImmobilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("types", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponibilite", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("images", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
